<?php

namespace App\Http\Requests;

use App\Enums\UserRole;
use Illuminate\Foundation\Http\FormRequest;

class StoreAcicRequest extends FormRequest
{
    public function authorize(): bool
    {
        return in_array($this->user()?->role, [UserRole::Admin, UserRole::Staff], true);
    }

    /**
     * The number is generated by the service, so there is nothing to validate.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [];
    }
}
