<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('acics', function (Blueprint $table) {
            $table->id();
            // Gap-free running sequence, generated by the system (never entered by hand).
            $table->unsignedInteger('acic_number')->unique();
            $table->string('status')->default('open'); // open | used | forwarded

            // Stamped when cheques are assigned ("Use ACIC").
            $table->foreignId('used_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('used_at')->nullable();

            // Stamped when the ACIC is forwarded on.
            $table->timestamp('forwarded_at')->nullable();
            $table->foreignId('received_by')->nullable()->constrained('users')->nullOnDelete();

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();

            $table->index('status');
        });

        Schema::table('cheques', function (Blueprint $table) {
            // A cheque belongs to at most one ACIC; the free-text accic_no is replaced by this link.
            $table->foreignId('acic_id')->nullable()->after('cheque_date')->constrained('acics')->nullOnDelete();
            $table->dropColumn('accic_no');
        });
    }

    public function down(): void
    {
        Schema::table('cheques', function (Blueprint $table) {
            $table->dropConstrainedForeignId('acic_id');
            $table->string('accic_no')->nullable()->after('cheque_date');
        });

        Schema::dropIfExists('acics');
    }
};
